# Generated by Django 5.2.8 on 2026-02-07 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='offer_type',
            field=models.CharField(choices=[('service', 'Services'), ('product', 'Produits'), ('both', 'Produits & services')], default='both', max_length=20),
        ),
        migrations.AddField(
            model_name='vendor',
            name='portfolio_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='services_overview',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='subscription_services',
            field=models.TextField(blank=True),
        ),
    ]
