# Generated by Django 6.0.2 on 2026-02-10 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0003_serviceprovider_servicerequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceprovider',
            name='id_document_back',
            field=models.ImageField(blank=True, null=True, upload_to='kyc/service_provider/id_back/'),
        ),
        migrations.AddField(
            model_name='serviceprovider',
            name='id_document_front',
            field=models.ImageField(blank=True, null=True, upload_to='kyc/service_provider/id_front/'),
        ),
        migrations.AddField(
            model_name='serviceprovider',
            name='id_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='serviceprovider',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='kyc/service_provider/photo/'),
        ),
        migrations.AddField(
            model_name='vendor',
            name='id_document_back',
            field=models.ImageField(blank=True, null=True, upload_to='kyc/vendor/id_back/'),
        ),
        migrations.AddField(
            model_name='vendor',
            name='id_document_front',
            field=models.ImageField(blank=True, null=True, upload_to='kyc/vendor/id_front/'),
        ),
        migrations.AddField(
            model_name='vendor',
            name='id_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='vendor',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='kyc/vendor/photo/'),
        ),
    ]
