# Generated by Django 6.0.2 on 2026-02-16 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0004_serviceprovider_id_document_back_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceprovider',
            name='email',
            field=models.EmailField(blank=True, max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='serviceprovider',
            name='id_number',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='email',
            field=models.EmailField(blank=True, max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='id_number',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
    ]
