# Generated by Django 5.2.8 on 2026-02-16 16:48

from django.db import migrations, models


def empty_email_to_null(apps, schema_editor):
    """Convertir les chaînes vides en NULL pour éviter les conflits UNIQUE."""
    Vendor = apps.get_model("marketplace", "Vendor")
    ServiceProvider = apps.get_model("marketplace", "ServiceProvider")
    Vendor.objects.filter(email="").update(email=None)
    ServiceProvider.objects.filter(email="").update(email=None)


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0005_alter_serviceprovider_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceprovider',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.RunPython(empty_email_to_null, migrations.RunPython.noop),
    ]
