# Generated by Django 6.0.2 on 2026-02-20 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0008_make_vendor_fields_required'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceprovider',
            name='email',
            field=models.EmailField(help_text='Email unique du prestataire de services (unique parmi toutes les boutiques et prestataires)', max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='serviceprovider',
            name='id_number',
            field=models.CharField(help_text="Numéro d'identité unique du prestataire (unique parmi toutes les boutiques et prestataires)", max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='email',
            field=models.EmailField(help_text='Email unique de la boutique (unique parmi toutes les boutiques et prestataires)', max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='id_number',
            field=models.CharField(help_text="Numéro d'identité unique (unique parmi toutes les boutiques et prestataires)", max_length=50, unique=True),
        ),
    ]
