# Generated by Django 5.2.8 on 2026-02-20 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0009_alter_serviceprovider_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceprovider',
            name='display_services_as_provider',
            field=models.BooleanField(default=False, help_text='Si coché, les services sont affichés en fiche prestataire (photo, badges, localisation). Sinon affichage produit classique.', verbose_name='Ce sont mes propres services que je propose'),
        ),
    ]
