# Generated by Django 6.0.2 on 2026-05-28 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0002_seed_default_plans'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptionpayment',
            name='provider',
            field=models.CharField(choices=[('card', 'Carte bancaire'), ('mobile_money', 'Mobile Money'), ('manual', 'Paiement manuel'), ('genius', 'GeniusPay (Wave, Orange, MTN, carte…)')], default='card', max_length=30),
        ),
    ]
