# Generated by Django 5.2.8 on 2026-02-07 16:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
        ('marketplace', '0003_serviceprovider_servicerequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='service_provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='marketplace.serviceprovider'),
        ),
    ]
