# Generated by Django 5.2.8 on 2026-02-16 16:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_product_service_provider'),
        ('marketplace', '0006_vendor_provider_email_nullable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product', to='marketplace.vendor'),
        ),
    ]
