# Generated by Django 6.0.2 on 2026-02-16 17:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_vendor_related_name_product'),
        ('marketplace', '0007_alter_serviceprovider_id_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='marketplace.vendor'),
        ),
    ]
