# Generated by Django 6.0.2 on 2026-05-28 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_categoryshowcaseimage_showcase_kind'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='categoryshowcaseimage',
            new_name='catalog_cat_categor_427b5b_idx',
            old_name='ctgshw_cv_pos',
        ),
        migrations.RenameIndex(
            model_name='categoryshowcaseimage',
            new_name='catalog_cat_categor_940eb3_idx',
            old_name='ctgshw_csp_pos',
        ),
    ]
