# Generated by Django 6.0.2 on 2026-04-18 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomepageBackground',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='homepage/backgrounds/')),
                ('title', models.CharField(blank=True, help_text='Libellé interne (facultatif), pour vous y retrouver.', max_length=120)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Image de fond (accueil)',
                'verbose_name_plural': 'Images de fond (accueil)',
                'ordering': ['-updated_at'],
            },
        ),
    ]
