# Generated by Django 6.0.2 on 2026-05-28 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('card', 'Carte bancaire'), ('mobile_money', 'Mobile Money'), ('paypal', 'PayPal'), ('local', 'Autre'), ('genius', 'Paiement en ligne (GeniusPay)')], default='card', max_length=50),
        ),
    ]
