# Generated by Django 6.0.2 on 2026-04-30 16:31

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MusicGenre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
                ('icon', models.CharField(blank=True, help_text='Émoji ou icône', max_length=10)),
                ('display_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Genre musical',
                'verbose_name_plural': 'Genres musicaux',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ArtistProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage_name', models.CharField(max_length=120, unique=True, verbose_name='nom de scène')),
                ('slug', models.SlugField(blank=True, max_length=140, unique=True)),
                ('bio', models.TextField(blank=True, verbose_name='biographie')),
                ('region', models.CharField(blank=True, help_text="Région ou ville d'origine", max_length=100)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('cover_photo', models.ImageField(blank=True, null=True, upload_to='culture/artists/covers/')),
                ('portrait', models.ImageField(blank=True, null=True, upload_to='culture/artists/portraits/')),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('whatsapp', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('website', models.URLField(blank=True)),
                ('facebook', models.URLField(blank=True)),
                ('instagram', models.URLField(blank=True)),
                ('youtube', models.URLField(blank=True)),
                ('tiktok', models.URLField(blank=True)),
                ('spotify', models.URLField(blank=True)),
                ('is_verified', models.BooleanField(default=False, help_text='Badge artiste vérifié')),
                ('is_featured', models.BooleanField(default=False, help_text="Mis en avant en page d'accueil")),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='artist_profile', to=settings.AUTH_USER_MODEL)),
                ('primary_genre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='artists', to='culture.musicgenre')),
            ],
            options={
                'verbose_name': 'Profil artiste',
                'verbose_name_plural': 'Profils artistes',
                'ordering': ['-is_featured', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180)),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('poster', models.ImageField(blank=True, null=True, upload_to='culture/events/posters/')),
                ('description', models.TextField()),
                ('starts_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('venue_name', models.CharField(max_length=180)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('region', models.CharField(blank=True, max_length=100)),
                ('map_url', models.URLField(blank=True, help_text='Lien Google Maps (optionnel)')),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('published', 'Publié'), ('cancelled', 'Annulé'), ('ended', 'Terminé')], default='draft', max_length=20)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_published', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('featured_artists', models.ManyToManyField(blank=True, related_name='events_featured', to='culture.artistprofile', verbose_name='Artistes invités')),
                ('headlining_artist', models.ForeignKey(blank=True, help_text="Artiste principal (tête d'affiche)", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='culture.artistprofile')),
                ('organizer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organized_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Concert / Événement',
                'verbose_name_plural': 'Concerts / Événements',
                'ordering': ['-is_featured', 'starts_at'],
            },
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160)),
                ('slug', models.SlugField(blank=True, max_length=180)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='culture/songs/covers/')),
                ('audio_file', models.FileField(help_text='Fichier MP3 ou WAV (audio file)', upload_to='culture/songs/audio/')),
                ('description', models.TextField(blank=True)),
                ('lyrics', models.TextField(blank=True, verbose_name='paroles')),
                ('release_date', models.DateField(blank=True, null=True)),
                ('duration_seconds', models.PositiveIntegerField(default=0, help_text='Durée en secondes')),
                ('pricing', models.CharField(choices=[('free', 'Gratuit (téléchargement libre)'), ('paid', 'Payant (téléchargement après achat)')], default='free', max_length=10)),
                ('price_fcfa', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('allow_streaming', models.BooleanField(default=True, help_text='Si coché, la chanson peut être écoutée gratuitement en streaming')),
                ('play_count', models.PositiveIntegerField(default=0)),
                ('download_count', models.PositiveIntegerField(default=0)),
                ('is_published', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='songs', to='culture.artistprofile')),
                ('genre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='songs', to='culture.musicgenre')),
            ],
            options={
                'ordering': ['-is_featured', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SongPurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_fcfa', models.DecimalField(decimal_places=2, max_digits=10)),
                ('reference', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('download_token', models.CharField(editable=False, max_length=64, unique=True)),
                ('is_paid', models.BooleanField(default=False)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('payment_method', models.CharField(blank=True, max_length=40)),
                ('download_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='culture.song')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='song_purchases', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Achat de chanson',
                'verbose_name_plural': 'Achats de chansons',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TicketCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Ex: Standard, VIP, Carré Or', max_length=80)),
                ('description', models.CharField(blank=True, help_text='Avantages inclus', max_length=255)),
                ('price_fcfa', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity_total', models.PositiveIntegerField(default=0)),
                ('quantity_sold', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('color', models.CharField(default='#C2410C', help_text='Couleur hex pour la badge billet', max_length=20)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_categories', to='culture.event')),
            ],
            options={
                'verbose_name': 'Catégorie de billet',
                'verbose_name_plural': 'Catégories de billets',
                'ordering': ['display_order', 'price_fcfa'],
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buyer_name', models.CharField(max_length=120)),
                ('buyer_email', models.EmailField(max_length=254)),
                ('buyer_phone', models.CharField(blank=True, max_length=30)),
                ('reference', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('secret_code', models.CharField(editable=False, max_length=64, unique=True)),
                ('status', models.CharField(choices=[('pending', 'En attente de paiement'), ('valid', 'Valide'), ('used', 'Utilisé'), ('cancelled', 'Annulé')], default='pending', max_length=20)),
                ('amount_fcfa', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_method', models.CharField(blank=True, max_length=40)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('used_by', models.CharField(blank=True, help_text='Nom du contrôleur qui a validé', max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('buyer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to=settings.AUTH_USER_MODEL)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tickets', to='culture.event')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tickets', to='culture.ticketcategory')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SongPlay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('played_at', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plays', to='culture.song')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-played_at'],
                'indexes': [models.Index(fields=['song', '-played_at'], name='culture_son_song_id_4f8d39_idx')],
            },
        ),
    ]
