# Generated by Django 6.0.2 on 2026-05-28 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('culture', '0004_event_digital_billboard'),
    ]

    operations = [
        migrations.AlterField(
            model_name='songpurchase',
            name='genius_reference',
            field=models.CharField(blank=True, default='', help_text="Référence GeniusPay (checkout) pour valider l'achat.", max_length=80),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='genius_reference',
            field=models.CharField(blank=True, default='', help_text='Référence GeniusPay commune à un lot de billets payés ensemble.', max_length=80),
        ),
    ]
